name: Build TWRP A15x

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib \
        libc6-dev-i386 libncurses5 libncurses5-dev lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev ccache \
        libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig openjdk-8-jdk python3 python3-pip rsync

    - name: Setup environment
      run: |
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        export PATH=~/bin:$PATH

    - name: Initialize repo
      run: |
        mkdir -p ~/twrp && cd ~/twrp
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
        repo sync -j4 --force-sync --no-clone-bundle --no-tags

    - name: Clone device, vendor, and kernel trees
      run: |
        cd ~/twrp
        git clone https://github.com/devhunter1/android_device_samsung_a15x device/samsung/a15x

        # Dummy vendor (kalau belum ada)
        if [ ! -d vendor/samsung/a15x ]; then
          mkdir -p vendor/samsung/a15x
          echo -e "LOCAL_PATH := \$(call my-dir)\ninclude \$(CLEAR_VARS)\nLOCAL_MODULE := dummy_vendor\ninclude \$(BUILD_PREBUILT)" > vendor/samsung/a15x/Android.mk
        fi

        # Dummy kernel (kalau belum ada)
        if [ ! -d kernel/samsung/a15x ]; then
          mkdir -p kernel/samsung/a15x
          echo -e "LOCAL_PATH := \$(call my-dir)\ninclude \$(CLEAR_VARS)\nLOCAL_MODULE := dummy_kernel\ninclude \$(BUILD_PREBUILT)" > kernel/samsung/a15x/Android.mk
        fi

    - name: Debug file tree
      run: |
        cd ~/twrp
        echo "=========== Directory Tree =========="
        find device/samsung/a15x | tee /tmp/device_tree.txt
        echo "=========== Vendor Tree =========="
        find vendor/samsung/a15x | tee /tmp/vendor_tree.txt
        echo "=========== Kernel Tree =========="
        find kernel/samsung/a15x | tee /tmp/kernel_tree.txt

    - name: Start TWRP build
      run: |
        set -x
        cd ~/twrp
        source build/envsetup.sh
        lunch twrp_a15x-eng
        make -j$(nproc) recoveryimage
