name: Build TWRP for A15 5G

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04  # lebih stabil daripada ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Set up build environment
        run: |
          sudo apt update
          sudo apt install -y bc bison build-essential ccache curl flex git gnupg gperf libncurses5-dev libssl-dev python3 python3-pip rsync unzip wget zip
          git config --global user.name "tata15-pixel"
          git config --global user.email "fitskyyt1121@gmail.com"

      - name: Initialize TWRP source
        run: |
          mkdir -p ~/twrp && cd ~/twrp
          repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
          repo sync -j$(nproc) --force-sync

      - name: Clone device tree
        run: |
          cd ~/twrp
          git clone https://github.com/devhunter1/android_device_samsung_a15x device/samsung/a15x

          # dummy kernel & vendor supaya build nggak error
          mkdir -p kernel/samsung/a15x
          echo "// dummy kernel" > kernel/samsung/a15x/Android.mk

          mkdir -p vendor/samsung/a15x
          echo "// dummy vendor" > vendor/samsung/a15x/Android.mk

      - name: Start TWRP build
        run: |
          cd ~/twrp
          source build/envsetup.sh
          lunch twrp_a15x-eng
          make -j$(nproc) recoveryimage

      - name: Upload output
        uses: actions/upload-artifact@v2  # versi stabil
        with:
          name: twrp-recovery.img
          path: ~/twrp/out/target/product/a15x/recovery.img
