name: Build TWRP for A15 5G

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git wget curl python3 openjdk-8-jdk bc bison build-essential ccache flex g++-multilib gcc-multilib gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev

      - name: Setup environment
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          mkdir -p ~/twrp && cd ~/twrp

      - name: Clone minimal manifest
        run: |
          cd ~
          mkdir -p twrp && cd twrp
          repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
          git clone https://github.com/tata15-pixel/android_device_samsung_a15x.git -b twrp device/samsung/a15x
          repo sync -j$(nproc --all)

      - name: Build TWRP
        run: |
          cd ~/twrp
          source build/envsetup.sh
          lunch twrp_a15x-eng
          mka recoveryimage

      - name: Upload recovery image
        uses: actions/upload-artifact@v3
        with:
          name: twrp-recovery
          path: ~/twrp/out/target/product/a15x/recovery.img
